# Generated by Django 3.0.4 on 2020-03-25 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200325_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogentry',
            old_name='question',
            new_name='article',
        ),
    ]
