# Generated by Django 3.0.4 on 2020-03-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_blogentry_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='subheading',
            field=models.CharField(default='', max_length=800),
        ),
    ]
